Print all build errors and do not stop after the first error
Example situation:
in the spec file, I had: "%{_libdir}/pulse/gsettings-helper" and I got an error that this file had not been found,
but in reality that file existed but in %{_libexecdir}/pulse/gsettings-helper.
I had to _guess_ that it exists. According to RPM log, it was not obvious.

RPM 5 printed both not found and unpackaged files, and this RPM 4 behaviour seems to cause waste of a lot of time.

Let's print both not found and not packaged files and all other errors that have happened.

TODO: eliminate *.debug from the output. Current output is like this:
error: Installed (but unpackaged) file(s) found:
   /usr/lib/debug/usr/lib64/pulse-13.0/modules/module-gsettings.so-13.0-2.x86_64.debug
   /usr/lib/debug/usr/libexec/pulse/gsettings-helper-13.0-2.x86_64.debug
   /usr/libexec/pulse/gsettings-helper
    File not found: /tmp/abf/rpmbuild/BUILDROOT/pulseaudio-13.0-2.x86_64/usr/lib64/pulse/gsettings-helper
    Installed (but unpackaged) file(s) found:
   /usr/lib/debug/usr/lib64/pulse-13.0/modules/module-gsettings.so-13.0-2.x86_64.debug
   /usr/lib/debug/usr/libexec/pulse/gsettings-helper-13.0-2.x86_64.debug
   /usr/libexec/pulse/gsettings-helper

Signed-off-by: Mikhail Novosyolov <m.novosyolov@rosalinux.ru>